using System.Collections.Generic;

public enum targetAnimation
{
    dblUp,
    dblDown,
    dblLeft,
    dblRight,
    triLeft,
    triRight,
    quadLeft,
    quadRight,
    stop3Sec,
    stop2Sec,
    leftSpinny,
    rightSpinny,
    leftThenCircleUp,
    rightThenCircleUp
}

public enum animationStep
{
    Left,
    Right,
    Up,
    Down,
    Spinny,
    SpinnyMirror,
    ZigZag,
    DownLow,
    Still,
    HalfcircleUpLeft,
    HalfcircleUpRight,
    HalfcircleDownLeft,
    HalfcircleDownRight
}

public static class AnimationDatabase
{
    public static readonly Dictionary<targetAnimation, animationStep[]> Animations = new()
    {
        {
            targetAnimation.dblUp,
            new[]
            {
                animationStep.Up,
                animationStep.Up
            }
        },
        {
            targetAnimation.dblDown,
            new[]
            {
                animationStep.Down,
                animationStep.Down
            }
        },
        {
            targetAnimation.dblLeft,
            new[]
            {
                animationStep.Left,
                animationStep.Left
            }
        },
        {
            targetAnimation.dblRight,
            new[]
            {
                animationStep.Right,
                animationStep.Right
            }
        },
        {
            targetAnimation.triLeft,
            new[]
            {
                animationStep.Left,
                animationStep.Left,
                animationStep.Left
            }
        },
        {
            targetAnimation.triRight,
            new[]
            {
                animationStep.Right,
                animationStep.Right,
                animationStep.Right
            }
        },
        {
            targetAnimation.quadLeft,
            new[]
            {
                animationStep.Left,
                animationStep.Left,
                animationStep.Left,
                animationStep.Left
            }
        },
        {
            targetAnimation.quadRight,
            new[]
            {
                animationStep.Right,
                animationStep.Right,               
                animationStep.Right,
                animationStep.Right
            }
        },
        {
            targetAnimation.stop3Sec,
            new[]
            {
                animationStep.Still,
                animationStep.Still,
                animationStep.Still
            }
        },
        {
            targetAnimation.stop2Sec,
            new[]
            {
                animationStep.Still,
                animationStep.Still
            }
        },
        {
            targetAnimation.leftSpinny,
            new[]
            {
                animationStep.Left,
                animationStep.Spinny
            }
        },
        {
            targetAnimation.rightSpinny,
            new[]
            {
                animationStep.Right,
                animationStep.SpinnyMirror
            }
        },
                {
        targetAnimation.leftThenCircleUp,
            new[]
            {
                animationStep.Left,
                animationStep.HalfcircleUpLeft,
                animationStep.HalfcircleDownRight,
                animationStep.HalfcircleUpLeft,
                animationStep.HalfcircleDownRight,
            }
        },
                        {
        targetAnimation.rightThenCircleUp,
            new[]
            {
                animationStep.Right,
                animationStep.HalfcircleUpRight,
                animationStep.HalfcircleDownLeft,
                animationStep.HalfcircleUpRight,
                animationStep.HalfcircleDownLeft,
            }
        },
    };
}